### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#10]
## Description

Create a Code of Conduct which the Mentors and Participants must abide by. 

## Additional Details

- Mention the Standards which everyone should abide by on welcoming and inclusive language including constructive criticism.
- Add the required responsibilities for Project Maintainers. 
- Mention the Scope of this Code of Conduct.

**Comment by shikharcodes** [comment]
Hey @HarshCasper, I have a template ready for this and want to add this file. Could you please assign me this issue?
