### ISSUE TITLE
Add a Github Action to auto-assign Mentors for every PR

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#11]
## Description 

Add a Github Action to auto-assign Mentors for every PR. It is a pain sometime to take a look at all the Projects for the PRs made by the Contributors. Getting a nice notification about reviewing a PR would make things easy for me. 

You can take a look at this [Github Action](https://github.com/marketplace/actions/auto-assign-action) for the purpose. Check [this](https://medium.com/better-programming/github-templates-the-smarter-way-to-formalize-pull-requests-among-development-teams-89f8d6a204f) out to know how to achieve the same.

**Comment by arnabsen1729** [comment]
@HarshCasper I would like to work on this issue. I was going through the Auto Assign Action it seems the reviewers list has to be static (hard-coded). Then we can create a couple of groups in this way:

```
 groupA:
    - reviewerA
    - reviewerB
    - reviewerC
  groupB:
    - reviewerD
    - reviewerE
    - reviewerF
   ```
   
  Do assign me the issue.

**Comment by Uyadav207** [comment]
I am GGSOC'21 participant, i would like to work on this issue.
@HarshCasper , please assign it to me: )

**Comment by HarshCasper** [comment]
Hi @arnabsen1729 

Will you be able to work on it on behalf of GSSoC '21 ? If yes, I will forward you the mentors that need to be assigned. 

@Uyadav207 Thanks for your interest. If @arnabsen1729 doesn't respond within a couple of days, you can take it up

**Comment by Uyadav207** [comment]
Thanks @HarshCasper

**Comment by arnabsen1729** [comment]
@HarshCasper yes, I would be working on behalf of GSSoC '21.

**Comment by arnabsen1729** [comment]
@HarshCasper will the mentors/reviewers have write perms to this repo? Accord to this [link](https://docs.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users)

>anyone who has commented on the issue or pull request, anyone with write permissions to the repository, and organization members with read permissions to the repository.

<hr>

For further queries should I continue this thread, or wait for the discord channels to be opened.

**Comment by HarshCasper** [comment]
Yes. Let me know once the action is ready and I will send you the list of all maintainers and mentors
