### ISSUE TITLE
Design the Login/Signup Page Design

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#12]
## Description

Create the Login/Signup Page Design in a widely-supported Design Software (Adobe XD/Figma).

## Contributors Guideline 

- Submissions should be made in an apt form so that Web Developers can work on them seamlessly. Make the PRs to the `design/` directory with the Adobe XD/Figma Files and a JPEG/PNG of them as well. Have separate folders for each page.
- The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.

**Comment by subhangi2731** [comment]
can you please assign it to me?

**Comment by HarshCasper** [comment]
Hi @subhangi2731 

Assigned you the same. Kindly forward me the designs before you make a PR through Discord. My Username is `harsh.bardhan.mishra#0810`. You can also forward me this through Mail [here](mailto:erbeusgriffincasper@gmail.com)

Do note that you have only three days to complete this, since we are on a critical timeline. Failure to communicate within three days might get you unassigned from this Issue

**Comment by HarshCasper** [comment]
Hi @subhangi2731 

Assigned you the same. Kindly forward me the designs before you make a PR through Discord. My Username is `harsh.bardhan.mishra#0810`. You can also forward me this through Mail [here](mailto:erbeusgriffincasper@gmail.com)

Do note that you have only three days to complete this, since we are on a critical timeline. Failure to communicate within three days might get you unassigned from this Issue

**Comment by subhangi2731** [comment]
I am working on this @HarshCasper but I have some doubts to ask for some implementation? In which discord channel should I reach you? is  there any separate one for this project??

**Comment by HarshCasper** [comment]
> I am working on this @HarshCasper but I have some doubts to ask for some implementation? In which discord channel should I reach you? is there any separate one for this project??

Please reach to me on #speak-ed on GSSoC Server. You can also drop me a message at `harsh.bardhan.mishra#0810`

**Comment by subhangi2731** [comment]
How to use grids and layouts in Adobexd @HarshCasper

**Comment by HarshCasper** [comment]
Hi @subhangi2731 

Just checking on, whether have you worked on it? I'm sorry, but I don't know about Adobe XD and have minimal knowledge over Figma. If you plan to work on this, please make a PR by Wednesday otherwise I would keep this Issue for assignment.

**Comment by A-HK** [comment]
Hey @HarshCasper , would love to work on this issue if nobody else is doing so.

**Comment by harshita2319** [comment]
I'd like to work on this issue! @HarshCasper

**Comment by subhangi2731** [comment]
@HarshCasper hey I am working on this and have designed in ADobe XD please give me some time till tomorrow morning I willl create a pr
