### ISSUE TITLE
Design a 404 Page for the Application

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#13]
## Description 

Add a 404 Page to keep a visitor on your site even if he/she hits a page that doesn't exist. This would also help us to change the Bad User experience to a positive one by adding some links to that 404 page so that the visitor can navigate to some other page.

## Contributors Guideline 

- Submissions should be made in an apt form so that Web Developers can work on them seamlessly. Make the PRs to the `design/` directory with the Adobe XD/Figma Files and a JPEG/PNG of them as well. Have separate folders for each page.
- The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.

**Comment by Tejas1510** [comment]
@HarshCasper Can i work on it

**Comment by HarshCasper** [comment]
> @HarshCasper Can i work on it

Yeah. Please use a prototyping software like Adobe XD or Figma for the purpose.

**Comment by subhangi2731** [comment]
can you please assign it to me?

**Comment by HarshCasper** [comment]
@subhangi2731 Please work on the Issue assigned to you.

**Comment by jain-rishabh-21** [comment]
Please assign it to me.
Discord Username: krackerzzz#4371

**Comment by ShambhaviSharma0110** [comment]
Hey, I'm interested in this project could you please allow me to work on it?

**Comment by jain-rishabh-21** [comment]
Hi shambhavi, I already raised a PR

**Comment by jain-rishabh-21** [comment]
Please close this issue, the PR is already merged
@HarshCasper
