### ISSUE TITLE
Design a Profile Page for the Application

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#14]
## Description 

Design a Profile Page.

## Contributors Guideline 

- Submissions should be made in an apt form so that Web Developers can work on them seamlessly. Make the PRs to the `design/` directory with the Adobe XD/Figma Files and a JPEG/PNG of them as well. Have separate folders for each page.
- The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.

**Comment by Tejas1510** [comment]
Can i work on it @HarshCasper

**Comment by HarshCasper** [comment]
> Can i work on it @HarshCasper

Yeah. Please use a prototyping software like Adobe XD or Figma for the purpose.

**Comment by jain-rishabh-21** [comment]
Please assign it to me 
Discord Username: krackerzzz#4371

**Comment by Hardik-07** [comment]
is this issue assigned , else I would like to contribute to it

**Comment by HarshCasper** [comment]
Hi @jain-rishabh-21

Would you still like to work on it? Please let me know at the earliest, or else I will assign this to @Hardik-07

**Comment by yaskpatel03** [comment]
I'm UI-UX designer let me know, if you need any help @HarshCasper

**Comment by subhangi2731** [comment]
@HarshCasper please assign this isssue to me
