### ISSUE TITLE
Design a Splash Screen

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#15]
## Description 

Design a Splash Screen which can either an animation or a GIF which can serve as a loading screen to give the end-user immediate feedback that an application is starting and loading in the background.

## Contributors Guideline 

- Submissions should be made in an apt form so that Web Developers can work on them seamlessly. Make the PRs to the `design/` directory with the Adobe XD/Figma Files and a JPEG/PNG of them as well. Have separate folders for each page.
- The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.

**Comment by subhangi2731** [comment]
can you please assign it to me?

**Comment by HarshCasper** [comment]
@subhangi2731 Please work on the Issue assigned to you.

**Comment by jain-rishabh-21** [comment]
Please assign it to me.
Discord Username: krackerzzz#4371
