### ISSUE TITLE
Add a Github Action to auto-assign Issues

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#16]
## Description

Add a Github Action to auto-assign Contributors. The Contributors can just type `/assign` and the Issue would be assigned to them by a Github Bot.

**Comment by Palash1999** [comment]
I would like to work on this.

**Comment by HarshCasper** [comment]
Assigned @Palash1999

**Comment by Siddhant-K-code** [comment]
@Palash1999 are you still working on the same?

**Comment by Palash1999** [comment]
@Siddhant-K-code No

**Comment by HarshCasper** [comment]
> @Palash1999 are you still working on the same?

If you would like to go ahead, let me know

**Comment by Siddhant-K-code** [comment]
yes, I can work upon this issue.

**Comment by Abhi-1313** [comment]
i can work on it

**Comment by arnabsen1729** [comment]
@Abhi-1313 what approach would you take?

**Comment by Abhi-1313** [comment]
> @Abhi-1313 what approach would you take?

@arnabsen1729 i am completely new to this ,it would be very helpful if you guide me  to what approch to follow

**Comment by jain-rishabh-21** [comment]
@HarshCasper If this is stale, please assign it to me!
Discord: krackerzzz#4371

**Comment by HarshCasper** [comment]
Hi @jain-rishabh-21 

Would you still like to work on it?

**Comment by Sukriti-sood** [comment]
@HarshCasper I would like to work on it.
