### ISSUE TITLE
Add React Boilerplate Code

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#2]
## Type

Advancement 

## Description

Add the React Boilerplate Code using `create-react-app` to the branch to get started with the UI Development using React. Make sure to add a `.gitignore` to prevent pushing up your `node-modules` as well.

## Tools

- NodeJS
- NPM
- Create React App CLI

**Comment by AnirudhPanda** [comment]
#5 pull request created.

**Comment by codewithvk** [comment]
I would like to work on this issue.
Can you assign me?

**Comment by SubhradeepSS** [comment]
@HarshCasper Can you assign me this issue for KWOC'20?

**Comment by Palash1999** [comment]
Can I work on this @HarshCasper ?

**Comment by CIPHERTron** [comment]
![Screenshot (301)](https://user-images.githubusercontent.com/56754747/102508434-63a0cd00-40ab-11eb-99c2-12746573a231.png)

@HarshCasper
