### ISSUE TITLE
No unit/integration tests in the project.

### ISSUE THREAD

**Issue by mohitms007** [HarshCasper/SpeakEd#25]
I will like to add some unit and integration test if possible using jest.

**Comment by mohitms007** [comment]
Tests are important part of any project as it makes the project less error prone and more reliable. Can I work on this?

**Comment by HarshCasper** [comment]
For sure @mohitms007 

Thanks for adding them.

**Comment by mohitms007** [comment]
Yeah I will start working on this! Thanks!
