### ISSUE TITLE
Design the Database Schema

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#26]
## Description

Design the Database Schema for the Application. The Database Schema should be worked on using a prototyping tool like Draw.io and should encompass the Community Manager, Public Speaker and the Admin Schemas. 

You can identify the various fields that we need to have from the perspective of a Social Application that brings Communities closer to Speakers and more.

**Comment by AnshMishra2001** [comment]
Can I also work on thid issue?

**Comment by aviiiij** [comment]
Hey, could this issue be assigned to me as well?

**Comment by HarshCasper** [comment]
@AnshMishra2001 @aviiiij 

Since this is a hard issue, I would love if you can collaborate on this. It would ensure that we can translate our best ideas into some good design. Let me know if both of you can collaborate on this. If yes, I will setup a Discord group where all of us can communicate.

**Comment by aviiiij** [comment]
Yes please. Would love to! :)

**Comment by HarshCasper** [comment]
Hi @aviiiij 

Since @AnshMishra2001 has not yet responded, I will assign you the Issue to you. I will soon send an invite for the Discord Server.

**Comment by AnshMishra2001** [comment]
@HarshCasper Sorry for late respone. I am also interested in working on this issue. I hope we can share the work.
