### ISSUE TITLE
Design Develop Header and Footer Components

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#27]
## Description 

Design and Develop Header and Footer Components which can be uniformly used across the spectrum of application.

You can prototype them on some prototyping tool like Adobe XD or Figma and share the designs with me on Discord/Mail before coding it out. We will be using `React-Bootstrap` as our primary UI Library so please stick to that for the convenience.

**Comment by GuptaTanisha** [comment]
@HarshCasper Please assign this to me.
