### ISSUE TITLE
Setup an Action to test the Frontend Build

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#28]
## Description

Create a Github Action which can be used to test the ReactJS Build in the `client` sub-directory with every commit and pull request. It is needed so that we don't introduce any breaking changes. 

You can have a look over how we can use Github Actions for the same. Even though using external tools like TravisCI or CircleCI are welcomed, it would be good to stick to Github Actions for the same.

**Comment by AnshMishra2001** [comment]
Pls assign this issue to me

**Comment by aviiiij** [comment]
Please assign me this issue!
