### ISSUE TITLE
Design and Develop a Landing Page

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#29]
## Description 

Develop the Landing Page of the Application. 

## Tutorials 

- [A Responsive Landing Page with React](https://medium.com/@roland1sankara/a-responsive-landing-page-with-react-3d9282e24b74)
- [Creating a Landing Page with React](https://www.youtube.com/watch?v=WV4ViZ2q0Mk)

You can come up with a wireframe before starting work on this. Having a wireframe ready would make it easy for us to communicate ideas and feedbacks easily.

**Comment by shristi99** [comment]
@HarshCasper  Please assign this to me.

**Comment by bhubesh757** [comment]
@HarshCasper Assign This issue To both of us ! @shristi99 Agree with Mine!! We can make a landing page together

**Comment by bhubesh757** [comment]
@HarshCasper Assign this issue to both! So the issue will be solved soon ! @shristi99 Agree with me.

**Comment by HarshCasper** [comment]
Hi @shristi99 and @bhubesh757 

Both of you can work together in my opinion. Once can develop a wireframe while the other can work on the code part. Both are equally important. 

Let me know if its feasible and I will assign you both

**Comment by bhubesh757** [comment]
@HarshCasper Thanks! Assign this to us and also in issue section just add a tag assigned
And One More if We do this together , does we will get equal points?? if not Assign This issue to @shristi99

**Comment by HarshCasper** [comment]
> @HarshCasper Thanks! Assign this to us and also in issue section just add a tag assigned
> And One More if We do this together , does we will get equal points?? if not Assign This issue to @shristi99

Both of you will get equal points. I'm waiting for @shristi99 response.

**Comment by shristi99** [comment]
Sure sir I am ready to work with @bhubesh757.

**Comment by HarshCasper** [comment]
@shristi99 @bhubesh757 

You can start the work. Remember that you should over communicate among each other. Try asking a lot of questions and clear up a lot of ideas you have in mind. And make sure to keep the thread here active along with on Discord while you are working on this.

**Comment by bhubesh757** [comment]
@HarshCasper Just Tell me what are components needed in the landing page! like header , footer

**Comment by HarshCasper** [comment]
Refer [this](https://learninbound.com/blog/8-essential-components-of-a-successful-landing-page/)

**Comment by ShambhaviSharma0110** [comment]
Hey, I'm interested in this project could you please allow me to work on it?
