### ISSUE TITLE
Add Flask Boilerplate

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#3]
## AIM 

Add Flask Application and create Mock endpoints for our Flask Application.

## Details

Flask is a micro web framework written in Python. It is classified as a microframework because it does not require particular tools or libraries. We will be using Flask-RESTful for creating the APIs which will interface with the MongoDB Database for Data Persistence.

You have to create basic mock endpoints which return a JSON Message on various routes.

**Comment by SubhradeepSS** [comment]
@HarshCasper can u assign me this issue for KWOC'20?

**Comment by krabhisharma** [comment]
@HarshCasper I will do this a point this to. Me.

**Comment by HarshCasper** [comment]
Assigned @krabhisharma 

Go for it 🚀

**Comment by HarshCasper** [comment]
Are you working on it @krabhisharma ?

**Comment by krabhisharma** [comment]
Sorry @HarshCasper  I was busy with My end sem exam .. I have made a pull request #23  kindly have a look to it...

**Comment by priyanshu20** [comment]
@HarshCasper Can I pick this up for GSSOC '21? Seems like the PR was left unmerged.

**Comment by HarshCasper** [comment]
> @HarshCasper Can I pick this up for GSSOC '21? Seems like the PR was left unmerged.

Hi @priyanshu20 

Assigning you the same
