### ISSUE TITLE
FrontEnd : Design and Develop Contact us Form! 

### ISSUE THREAD

**Issue by bhubesh757** [HarshCasper/SpeakEd#35]
**Is your feature request related to a problem? Please describe.**
yes
By Adding Contact us form , So the users can Reach you at any time , if any issues occur ! 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HarshCasper** [comment]
Go ahead! Be sure that the Contact Form would be a component and you can show a demo using Codepen/JSFiddle and not used in the App directly.

**Comment by bhubesh757** [comment]
@HarshCasper Sure I can Create a New ui design and  i will work on that!

**Comment by HarshCasper** [comment]
> @HarshCasper Sure I can Create a New ui design and i will work on that!

Awesome!

**Comment by HarshCasper** [comment]
Hi @bhubesh757 

Just checking, how has the progress been so far?

**Comment by bhubesh757** [comment]
@HarshCasper i am busy other issues please give  more days

**Comment by HarshCasper** [comment]
If you want, you can unassign yourself from the Issue.

**Comment by SnehaVeerakumar** [comment]
Can I work on this issue ?
If assigned 2 days of time is needed to solve this issue.
My suggestion : neumorphic design for the form.
