### ISSUE TITLE
Create the Login-Signup API Endpoints

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#36]
## Description 

Develop the User Schema of the Application and Login-Signup endpoints. It would be used for the purpose of authentication and authorization of the application. 

## Resources

- [Flask Login](https://flask-login.readthedocs.io/en/latest/)
- [Simple registration/login system with Flask, MongoDB, and BootStrap](https://medium.com/codex/simple-registration-login-system-with-flask-mongodb-and-bootstrap-8872b16ef915) 

Remember it would be a complete API-based interface so make necessary docs so that the API can be accessed using `cURL` as well.

**Comment by priyanshu20** [comment]
Hey Harsh,  I would like to take this up.
What will we be using for 
* MongoDB - pymongo,mongoalchemy or something else
* cookies or jwt and what is the preferred extension
* what file structure will we follow.

**Comment by HarshCasper** [comment]
> Hey Harsh, I would like to take this up.
> What will we be using for
> 
> * MongoDB - pymongo,mongoalchemy or something else
> * cookies or jwt and what is the preferred extension
> * what file structure will we follow.

- We should use PyMongo. Unlike the latter, it is well maintained and has community support.
- JWT 
- Factory Application Pattern should be preferred

**Comment by aviiiij** [comment]
Please assign this to me!

**Comment by Sukriti-sood** [comment]
@HarshCasper I wanted to work on this ,  I was thinking of Implementing it by Google or Can be Implemented by Form.
