### ISSUE TITLE
Add Unit Tests for the Flask Application

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#37]
## Description

Create Unit-Tests for the Flask Application using `pytest`. Add the `conftest.py` file and test the route responds with the Tests that you will be writing. Add a Github Action as well for Unit Tests to show if the Flask Application build is passing or failing.

## Tools

- PyTest 
- Python
- Github Actions
- Flask

**Comment by anjali1102** [comment]
Taking up

**Comment by Priyanshu078** [comment]
I am a GSSOC participant, can I work on this issue

**Comment by HarshCasper** [comment]
@anjali1102 Assigning this Issue to you.

@Priyanshu078 I will open more issues pretty soon :)

**Comment by Nishayadav-bit** [comment]
Hello, I am a GSSOC'21 participant . Please can you assign this issue to me .

**Comment by anjali1102** [comment]
@Nishayadav-bit  there are other more issues you can grab I am sure

**Comment by HarshCasper** [comment]
> @Nishayadav-bit there are other more issues you can grab I am sure

How has the progress been on this Issue? It has been 9 Days.

**Comment by jaiongit** [comment]
Taking up this issue.
