### ISSUE TITLE
Add Welcome + Stale Bot to the Application

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#38]
## Description 

This Issue requires two things: 

- Add a Github Action to mark stale Issues with a Tag. Issues that are not assigned, or has not been mentioned anywhere for more than 7 Days should be tagged with a "Stale" tag automatically.

- Add a Github Action that can welcome new contributors.

**Comment by anjali1102** [comment]
Taking up this issue

**Comment by HarshCasper** [comment]
@anjali1102 

The `/assign` bot is not setup on this project. We would need manual assigns. Would you want to create an issue for it and add it yourself 😉

**Comment by anjali1102** [comment]
Review #41 It's ok?

**Comment by anjali1102** [comment]
Review #50

**Comment by anjali1102** [comment]
The PR( #50 ) has been merged. You can close this issue
