### ISSUE TITLE
Dockerizing the project

### ISSUE THREAD

**Issue by jain-rishabh-21** [HarshCasper/SpeakEd#39]
**Is your feature request related to a problem? Please describe.**
It significantly reduces the time for setting up all the dependencies.

**Describe the solution you'd like**
Dockerizing the whole application will help developers not waste time setting up the environment.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by jain-rishabh-21** [comment]
If the issue is accepted please, please add the GSSOC'21 label and assign it to me.
Discord Username: krackerzzz#4371

**Comment by HarshCasper** [comment]
You may get started :)
