### ISSUE TITLE
Add Issue + PR Templates

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#4]
## AIM

Create a custom Issue and Pull Request Template.

## Features

- Make an Issue Template. Any new Contributor must be able to specify if it is a new script or enhancement to an older one. It should also be specified which language he is coding it in.

- Make a Pull Request Template. Any new Contributor must be able to specify if he has met all the requirements like Clean Code, proper README and Documentation, Screenshots (If any) attached and more.

**Comment by codewithvk** [comment]
I think it would be possible after frontend and backend setup.

**Comment by Tejas1510** [comment]
@HarshCasper Can I work on it

**Comment by HarshCasper** [comment]
Hello @Tejas1510 

Go ahead with it 🚀
