### ISSUE TITLE
Add Prettier for Application Build

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#57]
**Is your feature request related to a problem? Please describe.**
Add Prettier for Application Build. It would ensure that our CI pipeline and styling remains consistent throughout the development.

**Describe the solution you'd like**
You can have a look at various Prettier configurations. Here is the [one](https://github.com/manavm1990/front-end-starter) that I use but feel free to suggest your own configuation.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.
