### ISSUE TITLE
Add Husky Pre-Commit Hook

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#58]
**Is your feature request related to a problem? Please describe.**

Add Husky Pre-Commit Hook. Refer [this](https://www.freecodecamp.org/news/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks/) to get started. Make the apt README changes as well and make sure that it interfaces with the Prettier configuration that is part of this issue: https://github.com/HarshCasper/SpeakEd/issues/57

**Comment by noobkid2411** [comment]
Hi I would like to work on this issue!

**Comment by noobkid2411** [comment]
Hey @HarshCasper ,I had a doubt,the #67 pr has already added the husky precommit hook to the code to the package.json file. Do I need to add more precommit hooks to the same or just update the readme file? If I'm missing something, I'd like a bit of guidance on the same!
