### ISSUE TITLE
Add dark mode 

### ISSUE THREAD

**Issue by surbhi594** [HarshCasper/SpeakEd#65]

**Comment by surbhi594** [comment]
Please assign this issue to me as I'm a participant of the GSSOC'21.

**Comment by Abhishek765** [comment]
@surbhi594  let me know if you are not able to do that then I can handle this. I am also Gssoc21 participant

**Comment by arbazalam01** [comment]
can i work on this issue

**Comment by chazuttu** [comment]
I am GSSOC'21 Participant. Please assign this issue to me and review my PR for this issue. Thank you

**Comment by subhangi2731** [comment]
@HarshCasper please assign this issue to me
