### ISSUE TITLE
Create an Application Logo 

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#7]
## Description

Currently, we need a Logo for our Application which would be used on our Web Application Interface. 

# Tools

- Figma
- Adobe XD
- Adobe Photoshop 

## Additional Details

Logo Designs must be added in an appropriate form on the `assets/Logo-Design/` Directory. The basic criteria we are looking for are: 

- The logo should be optimized to a 500x500 Pixel Size.
- Transparent Background must be used. 
- Design Philosophy should be documented in the PR.

**Comment by tnahddisttud** [comment]
Hello, @HarshCasper! I'd like to work on this issue.

**Comment by subhangi2731** [comment]
can you assign it to me?

**Comment by abhishek7997** [comment]
Please assign it to me! I know how to use adobe photoshop and illustrator.
I have done a bit of graphic design as well.

Please take a look here: https://www.instagram.com/designxd_ai 
I made all the posts

**Comment by HarshCasper** [comment]
Hi @abhishek7997 

Loved your work. Assigned :tada:

**Comment by abhishek7997** [comment]
@HarshCasper Please check again, I have not been assigned this issue yet.

**Comment by abhishek7997** [comment]
@HarshCasper Sir, I will be make more than one logo design, do I have to commit all of them, or how can I show you which one do you want to pick?

**Comment by abhishek7997** [comment]
@HarshCasper Sir, there is no folder called assets, should I create one? Where should I create it?

**Comment by abhishek7997** [comment]
@HarshCasper Please check the new commit.

**Comment by HarshCasper** [comment]
@abhishek7997 Put all the designs in `design` directory

**Comment by abhishek7997** [comment]
@HarshCasper Please check the new commit.
