### ISSUE TITLE
Buttons Bug

### ISSUE THREAD

**Issue by Sristi27** [HarshCasper/SpeakEd#75]
**Describe the bug**
Buttons in the landing page are not properly aligned as per the page width

**To Reproduce**

**Expected behavior**
They should be perfectly aligned and placed right at the center

**Screenshots**
![Screenshot 2021-05-18 at 1 45 43 AM](https://user-images.githubusercontent.com/53037053/118550803-c4c3ee00-b77a-11eb-8e0b-55e47d84b00a.png)

**Desktop (please complete the following information):**
 - OS: [MACOs]
 - Browser [chrome]

**Additional context**

**Comment by tanishq-arya** [comment]
@HarshCasper this is a small fix. Can I raise a PR for this ?
