### ISSUE TITLE
Improve Cards

### ISSUE THREAD

**Issue by tanishq-arya** [HarshCasper/SpeakEd#79]
I would like to work on improving the speaker cards.
![image](https://user-images.githubusercontent.com/77333275/119791652-a2587000-bef2-11eb-8891-96b350f58f05.png)

**Comment by tanishq-arya** [comment]
@HarshCasper please assign me this issue.

**Comment by thakurbrajeshsingh** [comment]
@HarshCasper pls assign this issue to me

**Comment by tanishq-arya** [comment]
I am facing this error when I made a fresh pull.
![image](https://user-images.githubusercontent.com/77333275/120195537-8cbdb000-c23c-11eb-96e3-5efe603b3a94.png)

**Comment by tanishq-arya** [comment]
@HarshCasper I have raised a PR, if any changes are required do let me know.
