### ISSUE TITLE
Add a Contributor Guideline

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#8]
## Description

Create Contributors Guideline to help new Contributors get started with this Project.

## Additional Details

- Add a ```CONTRIBUTING.md``` to allow new users to get started with knowing how to contribute.
- Add Screenshots wherever possible. 
- Add the basic information about creating Issues, Pull Requests and Branching.
- Mention tutorials related to Git and Github to help them better understand.

**Comment by aysp-99** [comment]
Hi! Can I work on this issue?

**Comment by HarshCasper** [comment]
Hello @aysp-99 

I have assigned you the Issue 💯
