### ISSUE TITLE
Add DeepSource Static Code Analysis

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/SpeakEd#9]
## Description 

Add DeepSource Static Code Analysis on this Repository. 

## Additional Details 

- Fork the Repository (If you haven't already) 
- Go through the official [Documentation](https://deepsource.io/docs/analyzer/)
- Setup the `deepsource.toml` on the Root. 
- Make a PR. 

I will activate the analysis from my end to find Bugs and Anti-Patterns at every push.

**Comment by Siddhant-K-code** [comment]
we just want this for *JavaScript* right?

**Comment by CIPHERTron** [comment]
Can I work on this issue? @HarshCasper
